### ISSUE TITLE
hideSplashScreen() opacity issue

### ISSUE THREAD

**Issue by GitUser73937** [psal/anonymouth#4]
When running in eclipse in linux I get the below error :

```
Exception in thread "main" java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.
    at java.awt.Window.setOpacity(Window.java:3598)
    at java.awt.Frame.setOpacity(Frame.java:962)
    at edu.drexel.psal.anonymouth.gooie.SplashScreen.hideSplashScreen(SplashScreen.java:154)
    at edu.drexel.psal.anonymouth.gooie.ThePresident.<init>(ThePresident.java:164)
    at edu.drexel.psal.anonymouth.gooie.ThePresident.main(ThePresident.java:70)
```

I was able to rectify this by removing line 154 in SplashScreen.java

**Comment by krouskop** [comment]
I encountered the same error and also got around it by commenting out all but `splashScreen.setVisible(false);` in <code>hideSplashScreen()</code>.

FWIW, the JavaSE tutorial has this recommendation on [Determining a Platform's Capabilities](https://docs.oracle.com/javase/tutorial/uiswing/misc/trans_shaped_windows.html#capability) in this regard.

> Not all platforms support all of these capabilities. An <code>UnsupportedOperationException</code> exception is thrown when code attempts to invoke the <code>setShape</code> or <code>setOpacity</code> methods on a platform that does not support these capabilities. Therefore, it is best practice to first check that the platform supports the capability that you want to implement. The <code>GraphicsDevice</code> class provides the 
> <a href="https://docs.oracle.com/javase/8/docs/api/java/awt/GraphicsDevice.html#isWindowTranslucencySupported-java.awt.GraphicsDevice.WindowTranslucency-"><code>isWindowTranslucencySupported(GraphicsDevice.WindowTranslucency)</code></a> method that you can use for this purpose. You pass one of three enum values, defined in 
> <a href="https://docs.oracle.com/javase/8/docs/api/java/awt/GraphicsDevice.WindowTranslucency.html"><code>GraphicsDevice.WindowTranslucency</code></a>, to this method:
> *<code>TRANSLUCENT</code> – The underlying platform supports windows with uniform translucency, where each pixel has the same alpha value.</li>
> *<code>PERPIXEL_TRANSLUCENT</code> – The underlying platform supports windows with per-pixel translucency. This capability is required to implement windows that fade away.</li>
> *<code>PERPIXEL_TRANSPARENT</code> – The underlying platform supports shaped windows.</li>
> 
> The <code>GraphicsConfiguration</code> class also provides the 
> <a href="https://docs.oracle.com/javase/8/docs/api/java/awt/GraphicsConfiguration.html#isTranslucencyCapable--"><code>isTranslucencyCapable</code></a> method to determine if <code>PERPIXEL_TRANSLUCENT</code> translucency is supported by the given <code>GraphicsConfiguration</code> object.
> 
> The following code shows how to check for all three capabilities:
> 
> ```
> import static java.awt.GraphicsDevice.WindowTranslucency.*;
> 
> // Determine what the default GraphicsDevice can support.
> GraphicsEnvironment ge =
>     GraphicsEnvironment.getLocalGraphicsEnvironment();
> GraphicsDevice gd = ge.getDefaultScreenDevice();
> 
> boolean isUniformTranslucencySupported =
>     gd.isWindowTranslucencySupported(TRANSLUCENT);
> boolean isPerPixelTranslucencySupported =
>     gd.isWindowTranslucencySupported(PERPIXEL_TRANSLUCENT);
> boolean isShapedWindowSupported =
>     gd.isWindowTranslucencySupported(PERPIXEL_TRANSPARENT);
> ```
